### PR TITLE
Updates error model to include params from API

### PR DESCRIPTION
**Pull request by tojroob**
Most of the params sent from the API are lists of strings, but there are some edge cases where params is a list of numbers or just a string.
Converts various params typing from the API into a List of strings.

### CODE REVIEW

**Comment by bryceremick** [comment]
@tojroob ASssuming that the `params` field will be typed as `dynamic` , what are your plans on the manager app for checking for specific errors? e.g. notifying the user of a duplicate pin code on the user creation flow

**Comment by tojroob** [comment]
@bryceremick In the cubit level, I was planning on doing a type check and then a contains check. Something like this:
```
  if (params is List) {
    if (params.contains('emailAddress')) {
      //handle error state
    }
```

**Comment by bryceremick** [comment]
Gotcha. I don't think that implementation is wrong, but I worry that it could introduce a lot of "duplicate" code throughout the manager app. Do you think it would be better to abstract this kind of logic away from the manager app? i.e. have this logic live in the dual sdk `ServerError` model

**Comment by tojroob** [comment]
Yeah we could do that instead. I could check for params typing and change it to always be a List<String> for the Manager app.

**Review by bryceremick — APPROVED** [review]

**Pull request merged**
